### ISSUE TITLE
  FileNotFoundException when form with upload function

### ISSUE THREAD

**Issue by jhhazelaar** [anakadote/statamic-recaptcha#15]
Hi,

We ran into a big issue with using the addon and a form with upload field. We get this error when submitting a form:

```
Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException: The file &quot;/private/var/tmp/phpRkXJ8X&quot; does not exist in file /statamic-recaptcha/vendor/symfony/http-foundation/File/File.php on line 36

#0 /statamic-recaptcha/vendor/symfony/http-foundation/File/UploadedFile.php(70): Symfony\Component\HttpFoundation\File\File-&gt;__construct(&#039;/private/var/tm...&#039;, true)
#1 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/UploadedFile.php(134): Symfony\Component\HttpFoundation\File\UploadedFile-&gt;__construct(&#039;/private/var/tm...&#039;, &#039;Screenshot 2024...&#039;, &#039;image/png&#039;, 0, false)
#2 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(540): Illuminate\Http\UploadedFile::createFromBase(Object(Symfony\Component\HttpFoundation\File\UploadedFile))
#3 [internal function]: Illuminate\Http\Request-&gt;Illuminate\Http\Concerns\{closure}(Object(Symfony\Component\HttpFoundation\File\UploadedFile))
#4 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(533): array_map(Object(Closure), Array)
#5 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(539): Illuminate\Http\Request-&gt;convertUploadedFiles(Array)
#6 [internal function]: Illuminate\Http\Request-&gt;Illuminate\Http\Concerns\{closure}(Array)
#7 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(533): array_map(Object(Closure), Array)
#8 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(522): Illuminate\Http\Request-&gt;convertUploadedFiles(Array)
#9 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(279): Illuminate\Http\Request-&gt;allFiles()
#10 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/Request.php(789): Illuminate\Http\Request-&gt;all()
#11 /statamic-recaptcha/vendor/anakadote/statamic-recaptcha/src/Listeners/VerifyRecaptcha.php(30): Illuminate\Http\Request-&gt;__get(&#039;captcha_token&#039;)
#12 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): Anakadote\StatamicRecaptcha\Listeners\VerifyRecaptcha-&gt;handle(Object(Statamic\Events\FormSubmitted))
#13 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\Events\Dispatcher-&gt;Illuminate\Events\{closure}(&#039;Statamic\\Events...&#039;, Array)
#14 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\Events\Dispatcher-&gt;invokeListeners(&#039;Statamic\\Events...&#039;, Array, true)
#15 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(433): Illuminate\Events\Dispatcher-&gt;dispatch(&#039;Statamic\\Events...&#039;, Array, true)
#16 /statamic-recaptcha/vendor/statamic/cms/src/Events/FormSubmitted.php(23): event(Object(Statamic\Events\FormSubmitted), Array, true)
#17 /statamic-recaptcha/vendor/statamic/cms/src/Http/Controllers/FormController.php(61): Statamic\Events\FormSubmitted::dispatch(Object(Statamic\Forms\Submission))
#18 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\Http\Controllers\FormController-&gt;submit(Object(Statamic\Http\Requests\FrontendFormRequest), Object(Statamic\Forms\Form))
#19 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller-&gt;callAction(&#039;submit&#039;, Array)
#20 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(Statamic\Http\Controllers\FormController), &#039;submit&#039;)
#21 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route-&gt;runController()
#22 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Route-&gt;run()
#23 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#32 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/HandlePrecognitiveRequests.php(41): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\HandlePrecognitiveRequests-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /statamic-recaptcha/vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php(24): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Rias\StatamicRedirect\Http\Middleware\HandleNotFound-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#43 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#44 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#45 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#46 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#47 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#48 /statamic-recaptcha/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\StopImpersonating-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /statamic-recaptcha/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\DisableFloc-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /statamic-recaptcha/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\CheckMultisite-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /statamic-recaptcha/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\CheckComposerJsonScripts-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /statamic-recaptcha/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\PoweredByHeader-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /statamic-recaptcha/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\Debugbar\Middleware\InjectDebugbar-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#76 /statamic-recaptcha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#77 /statamic-recaptcha/public/index.php(51): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#78 /Users/janhenk/.composer/vendor/laravel/valet/server.php(110): require(&#039;/Users/janhenk/...&#039;)
#79 {main}
```

Support detail:

```
Environment
Application Name: Statamic
Laravel Version: 10.41.0
PHP Version: 8.3.1
Composer Version: 2.6.6
Environment: local
Debug Mode: ENABLED
URL: statamic.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily, flare
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.45.0 PRO

Statamic Addons
anakadote/statamic-recaptcha: 1.0.12
rias/statamic-redirect: 3.6.0
statamic/seo-pro: 5.4.1
```

**Comment by jhhazelaar** [comment]
Looks like the `request()` in the listener gives this exception. When searching a came a cross tips that this error happens when the request get called twice and it looks like that is happing here.

If you comment these lines out, it work. So maybe another solution to check the recaptcha is valid is to use middleware?

**Comment by k-aleksandar** [comment]
Hi, we experience the same bug when a form is submitted with a file. The reason for the bug is that the listener statamic-addon-recaptcha/src/Listeners/VerifyRecaptcha.php cannot access the request dynamic properties on lines 30 and 31, for some reason the request is different from when we don't have a file in the form, to fix the bug we can use the request method get() in both cases which means replacing line 30 with `$token = request()->get('captcha_token');` and 31 accordingly.

**Comment by anakadote** [comment]
@k-aleksandar the latest release addresses your issue by replacing the dynamic properties with Laravel's Request::input() method. Please let me know if that resolves your issue.

**Comment by k-aleksandar** [comment]
@anakadote yes it is fixing the bug. Thank you for the fast replay.
